# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8ac5475d5db2fb7b01f200482c1debdc0aa3c21f4f1c7de7b6ebba0d8727ddb31f4deba684322748906a6b2d52f183d9da61159663b513b1529be814e29da7a

test:
  secret_key_base: e9d514614a7e787af8b1c14a87b7d112396f5f0e3db219ec1fc0d2dfc4c4f30746a0a9a7ae55275b56df4f4fc979d17d73d99d6612c4871dff36771281befc25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
